package kusljic.mihajlo.sbnz.spring.backend.facts;

public enum ObservationType {
	
	BEGINNER_FRIENDLY, CARGO_FRIENDLY, CITY_FRIENDLY, CONNECTIVITY_SUPPORTED, FAMILY_FRIENDLY, OFFROAD_FRIENDLY,
	SPORT_FRIENDLY, TRAVEL_FRIENDLY, FUEL_EFFICIENT, LOW_REGISTRATION_COSTS, SERVICING_FRIENDLY

}
