package sbnz.integracija;

import kusljic.mihajlo.sbnz.spring.backend.facts.AccountLock;
import kusljic.mihajlo.sbnz.spring.backend.facts.CarModel;
import kusljic.mihajlo.sbnz.spring.backend.facts.Conformance;
import kusljic.mihajlo.sbnz.spring.backend.facts.Observation;
import kusljic.mihajlo.sbnz.spring.backend.facts.Recommendation

query "Fetch observations for car model" (CarModel $model)
	$o: Observation(carModel == $model)
end

query "Fetch car model" (CarModel $model)
	$cm: CarModel(this == $model)
end

query "Fetch conformances"
	$c: Conformance()
end

query "Fetch recommendations"
	$r: Recommendation()
end

query "Fetch all account locks"
	$al: AccountLock()
end

query "Fetch locks for account" (String $username)
	$al: AccountLock(username.equals($username))
end
